#! /usr/bin/env python
# encoding: utf-8
'''
@file wscript
@brief This is the main Waf based build sytem file for SSE-ImGui

This file is part of Skyrim SE ImGui mod project (aka SSE-ImGui).

  SSE-ImGui is free software: you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  SSE-ImGui is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with SSE-ImGui. If not, see <http://www.gnu.org/licenses/>.

@endinternal

@ingroup Builds

@details
Waf is Python (2/3) based build system similar to SCons & Make.
@see https://waf.io/book/
'''

import os

#---------------------------------------------------------------------------------------------------

top = '.'
out = 'out'
APPNAME = 'sse-imgui-demo'
VERSION = '1.1.0'

#---------------------------------------------------------------------------------------------------

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

    if conf.env['CXX_NAME'] == 'gcc':
        conf.check_cxx (msg="Checking for '-std=c++20'", cxxflags='-std=c++20') 
        conf.env.append_unique('CXXFLAGS', ['-std=c++20', "-O2", "-Wall"])
        conf.env.append_unique ('STLIB', ['stdc++', 'pthread'])
        conf.env.append_unique ('LINKFLAGS', ['-static-libgcc', '-static-libstdc++'])

def build (bld):
    bld.shlib (target = APPNAME, source = bld.path.ant_glob ("*.cpp"), includes = '../../include')

#---------------------------------------------------------------------------------------------------

